steps:
  # 1. Start Cloud SQL Proxy in background
  - id: start-proxy
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker run -d --name cloud-sql-proxy --network=cloudbuild \
          gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0 \
          --address=0.0.0.0 --port=5432 \
          ${_INSTANCE_CONNECTION_NAME}
        sleep 10 # Give it time to connect

  # 2. Run Migrations
  - id: migrate
    name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd backend
        npm install
        npx prisma migrate deploy
    env:
      # Connect to the proxy container by name on port 5432
      - "DATABASE_URL=postgresql://${_DB_USER}:${_DB_PASSWORD}@cloud-sql-proxy:5432/${_DB_NAME}?sslmode=disable"

  # 3. Cleanup Proxy
  - id: cleanup
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker rm -f cloud-sql-proxy || true']

options:
  substitution_option: ALLOW_LOOSE

timeout: 1200s

substitutions:
  _INSTANCE_CONNECTION_NAME: project:region:instance
  _DB_USER: doribharat_app
  _DB_PASSWORD: change-me
  _DB_NAME: doribharat
